###

GET http://localhost:4000/users/get-user

###

GET http://localhost:4000

###
POST http://localhost:4000/users/create-user
Content-Type: application/json

{
    "username":"Vinay79",
    "password":"Vinay"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "username":"Vinay79",
    "password":"Vinay"
}


###
POST http://localhost:5000/diary/create-data
Content-Type: application/json

{
    "date":"date",
    "data":"This is diary data",
    "username":"Vinay7"
}


###
GET http://localhost:4000/diary/get-data

###

DELETE http://localhost:4000/diary/del-data/Vinay7/date


###

GET http://localhost:5000/diary/get-person/Vinay7